---
version: 2.1
orbs:
  samvera: samvera/circleci-orb@0
jobs:
  bundle:
    parameters:
      ruby_version:
        type: string
        default: 2.6.3
      bundler_version:
        type: string
        default: 1.17.3
      rails_version:
        type: string
        default: '5.2.3'
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    environment:
      RAILS_VERSION: << parameters.rails_version >>
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - samvera/cached_checkout
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: hydra-role-management
      - persist_to_workspace:
          root: ~/
          paths:
          - project/*
          - project/**/*
  lint:
    parameters:
      ruby_version:
        type: string
        default: 2.6.3
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    steps:
      - attach_workspace:
          at: ~/
      - samvera/rubocop
  build:
    parameters:
      ruby_version:
        type: string
        default: 2.6.3
      bundler_version:
        type: string
        default: 1.17.3
      rails_version:
        type: string
        default: '5.2.3'
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    environment:
      RAILS_VERSION: << parameters.rails_version >>
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      ENGINE_CART_RAILS_OPTIONS: --skip-git --skip-bundle --skip-listen --skip-spring --skip-yarn --skip-keeps --skip-action-cable --skip-coffee --skip-puma --skip-test
    steps:
      - attach_workspace:
          at: ~/
      - samvera/engine_cart_generate:
          cache_key: v1-internal-test-app-{{ checksum "hydra-role-management.gemspec" }}-{{ checksum "spec/test_app_templates/lib/generators/test_app_generator.rb" }}-{{ checksum "lib/generators/roles/roles_generator.rb" }}-<< parameters.rails_version >>-<< parameters.ruby_version >>
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: hydra-role-management
      - persist_to_workspace:
          root: ~/
          paths:
          - project/*
          - project/**/*
  test:
    parameters:
      ruby_version:
        type: string
        default: 2.6.3
      bundler_version:
        type: string
        default: 1.17.3
    executor:
      name: 'samvera/ruby_fcrepo_solr'
      ruby_version: << parameters.ruby_version >>
    steps:
      - attach_workspace:
          at: ~/
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: hydra-role-management
      - samvera/parallel_rspec

workflows:
  ci:
    jobs:
      - bundle:
          name: "bundle_ruby2-6_rails5-2"
          ruby_version: "2.6.3"
          rails_version: "5.2.3"
      - lint:
          name: "lint_ruby2-6_rails5-2"
          ruby_version: "2.6.3"
          requires:
            - bundle_ruby2-6_rails5-2
      - build:
          name: "build_ruby2-6_rails5-2"
          ruby_version: "2.6.3"
          rails_version: "5.2.3"
          requires:
            - bundle_ruby2-6_rails5-2
      - test:
          name: "ruby2-6_rails5-2"
          ruby_version: "2.6.3"
          requires:
            - build_ruby2-6_rails5-2
      - bundle:
          name: "bundle_ruby2-5_rails5-2"
          ruby_version: "2.5.5"
          rails_version: "5.2.3"
      - lint:
          name: "lint_ruby2-5_rails5-2"
          ruby_version: "2.5.5"
          requires:
            - bundle_ruby2-5_rails5-2
      - build:
          name: "build_ruby2-5_rails5-2"
          ruby_version: "2.5.5"
          rails_version: "5.2.3"
          requires:
            - bundle_ruby2-5_rails5-2
      - test:
          name: "ruby2-5_rails5-2"
          ruby_version: "2.5.5"
          requires:
            - build_ruby2-5_rails5-2
      - bundle:
          name: "bundle_ruby2-4_rails5-2"
          ruby_version: "2.4.6"
          rails_version: "5.2.3"
      - lint:
          name: "lint_ruby2-4_rails5-2"
          ruby_version: "2.4.6"
          requires:
            - bundle_ruby2-4_rails5-2
      - build:
          name: "build_ruby2-4_rails5-2"
          ruby_version: "2.4.6"
          rails_version: "5.2.3"
          requires:
            - bundle_ruby2-4_rails5-2
      - test:
          name: "ruby2-4_rails5-2"
          ruby_version: "2.4.6"
          requires:
            - build_ruby2-4_rails5-2
